spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/food-recipe-bot-base
    username: postgres
    password: root777
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-circular-references: true
telegram:
  bot:
    username: "@Cook_Pal_Bot"
    token: "8235955047:AAHbKUD8ZuMIVYXWWZuQS-HWC_i35e8v10s"